spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/laundryhub}
    username: ${DB_USER:laundry}
    password: ${DB_PASSWORD:laundry}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  thymeleaf:
    cache: false
server:
  port: ${PORT:8080}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
