-- =====================================================================
-- LaundryHub — V1__init_schema.sql   (PostgreSQL)
-- วางที่: code/src/main/resources/db/migration/V1__init_schema.sql
-- ร่างเริ่มต้น: โอ๊คตรวจ + ทีมตกลงร่วมกันภายใน 3 ชม.แรก แล้ว "ล็อก"
-- หลังล็อกห้ามแก้ไฟล์นี้ ถ้าต้องเปลี่ยนให้เพิ่ม V3__xxx.sql
-- =====================================================================

-- 1) users  (1:1 customer_profiles)
CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(50)  NOT NULL UNIQUE,
    email       VARCHAR(100) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    role        VARCHAR(20)  NOT NULL,
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_users_role CHECK (role IN ('CUSTOMER', 'STAFF', 'ADMIN'))
);

-- 2) customer_profiles  (1:1 users)
CREATE TABLE customer_profiles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL UNIQUE,
    full_name   VARCHAR(100) NOT NULL,
    phone       VARCHAR(20),
    address     VARCHAR(255),
    CONSTRAINT fk_profile_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 3) branches  (1:N machines)
CREATE TABLE branches (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    address     VARCHAR(255),
    phone       VARCHAR(20)
);

-- 4) service_types  (1:N laundry_order_items)
CREATE TABLE service_types (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(100)   NOT NULL UNIQUE,
    price_per_kg       NUMERIC(10, 2) NOT NULL CHECK (price_per_kg >= 0),
    express_surcharge  NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (express_surcharge >= 0),
    active             BOOLEAN        NOT NULL DEFAULT TRUE
);

-- 5) laundry_orders  (N:1 users, N:1 branches, 1:N items, 1:1 payments)
CREATE TABLE laundry_orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT         NOT NULL,
    branch_id       BIGINT         NOT NULL,
    status          VARCHAR(20)    NOT NULL DEFAULT 'RECEIVED',
    express         BOOLEAN        NOT NULL DEFAULT FALSE,
    total_weight_kg NUMERIC(8, 2)  NOT NULL DEFAULT 0,
    total_amount    NUMERIC(10, 2) NOT NULL DEFAULT 0,
    note            VARCHAR(255),
    created_at      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_user   FOREIGN KEY (user_id)   REFERENCES users (id),
    CONSTRAINT fk_order_branch FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT chk_order_status CHECK (status IN
        ('RECEIVED', 'WASHING', 'DRYING', 'IRONING', 'READY', 'PICKED_UP', 'CANCELLED'))
);

-- 6) laundry_order_items  (N:1 laundry_orders, N:1 service_types)
CREATE TABLE laundry_order_items (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT         NOT NULL,
    service_type_id  BIGINT         NOT NULL,
    item_name        VARCHAR(100)   NOT NULL,
    weight_kg        NUMERIC(8, 2)  NOT NULL CHECK (weight_kg > 0),
    subtotal         NUMERIC(10, 2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_item_order        FOREIGN KEY (order_id)        REFERENCES laundry_orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_item_service_type FOREIGN KEY (service_type_id) REFERENCES service_types (id)
);

-- 7) machines  (N:1 branches, 1:N usage_sessions)
CREATE TABLE machines (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id         BIGINT         NOT NULL,
    name              VARCHAR(50)    NOT NULL,
    machine_type      VARCHAR(10)    NOT NULL,
    status            VARCHAR(20)    NOT NULL DEFAULT 'AVAILABLE',
    base_price        NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (base_price >= 0),
    price_per_minute  NUMERIC(8, 2)  NOT NULL DEFAULT 0 CHECK (price_per_minute >= 0),
    CONSTRAINT fk_machine_branch FOREIGN KEY (branch_id) REFERENCES branches (id),
    CONSTRAINT chk_machine_type   CHECK (machine_type IN ('WASHER', 'DRYER')),
    CONSTRAINT chk_machine_status CHECK (status IN ('AVAILABLE', 'RESERVED', 'IN_USE', 'OUT_OF_SERVICE')),
    CONSTRAINT uq_machine_branch_name UNIQUE (branch_id, name)
);

-- 8) usage_sessions  (N:1 machines, N:1 users, 1:1 payments)
CREATE TABLE usage_sessions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id        BIGINT         NOT NULL,
    user_id           BIGINT         NOT NULL,
    status            VARCHAR(20)    NOT NULL DEFAULT 'RESERVED',
    start_time        TIMESTAMP      NOT NULL,
    end_time          TIMESTAMP      NOT NULL,
    duration_minutes  INT            NOT NULL CHECK (duration_minutes > 0),
    amount            NUMERIC(10, 2) NOT NULL DEFAULT 0,
    created_at        TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_session_machine FOREIGN KEY (machine_id) REFERENCES machines (id),
    CONSTRAINT fk_session_user    FOREIGN KEY (user_id)    REFERENCES users (id),
    CONSTRAINT chk_session_status CHECK (status IN ('RESERVED', 'IN_USE', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT chk_session_time   CHECK (end_time > start_time)
);

-- 9) payments  (1:1 laundry_orders  หรือ  1:1 usage_sessions — อย่างใดอย่างหนึ่ง)
CREATE TABLE payments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT UNIQUE,
    session_id  BIGINT UNIQUE,
    amount      NUMERIC(10, 2) NOT NULL CHECK (amount >= 0),
    method      VARCHAR(20)    NOT NULL,
    status      VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    paid_at     TIMESTAMP,
    created_at  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_order   FOREIGN KEY (order_id)   REFERENCES laundry_orders (id),
    CONSTRAINT fk_payment_session FOREIGN KEY (session_id) REFERENCES usage_sessions (id),
    CONSTRAINT chk_payment_method CHECK (method IN ('CASH', 'QR_MOCK', 'COIN')),
    CONSTRAINT chk_payment_status CHECK (status IN ('PENDING', 'PAID', 'FAILED')),
    CONSTRAINT chk_payment_target CHECK (
        (order_id IS NOT NULL AND session_id IS NULL) OR
        (order_id IS NULL AND session_id IS NOT NULL))
);

-- 10) notifications  (N:1 users)
CREATE TABLE notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    message     VARCHAR(255) NOT NULL,
    is_read     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
-- Index (เหตุผลจะเขียนใน data-dictionary.md)
-- ---------------------------------------------------------------------
CREATE INDEX idx_orders_user_status       ON laundry_orders (user_id, status);
CREATE INDEX idx_orders_branch            ON laundry_orders (branch_id);
CREATE INDEX idx_items_order              ON laundry_order_items (order_id);
CREATE INDEX idx_machines_branch_status   ON machines (branch_id, status);
CREATE INDEX idx_sessions_machine_time    ON usage_sessions (machine_id, start_time, end_time);
CREATE INDEX idx_sessions_user            ON usage_sessions (user_id);
CREATE INDEX idx_notifications_user_read  ON notifications (user_id, is_read);
